<?php if(extension_loaded('zlib')){ob_start('ob_gzhandler');} header("Content-type: text/javascript"); ?>
var cazu={init:function(){this.$window=$(window);this.$body=$("body");this.$article=$("article").eq(0);window.pageID||(window.pageID=this.getPage());this.currentMenu().headerMov().disableButtons();switch(window.pageID){case "home":this.portfolioGrid().portfolioItemAjax();break;case "blog-list":this.searchForm();break;case "blog-post":this.searchForm().wpCaptionOnFull().preHighlight().wipSlide().validateForm();break;case "portfolio-list":this.portfolioGrid().portfolioItemAjax();break;case "page":this.preHighlight().getBubble()}return this},
getPage:function(){var a=this.$article.attr("id");if(void 0==a||""==a)a="portfolio";return a},headerMov:function(){var a=this,b=$("header.main"),e=this.$window.scrollTop(),c=0,d=!0,k=$("#menu-launcher"),g=!1,h=function(a){a&&!g&&(b.addClass("opened-menu"),setTimeout(function(){g=!0},500));g&&(b.removeClass("opened-menu"),setTimeout(function(){g=!1},500))},f=!1,l=function(){var c=a.$window.width();768>=c&&!f&&($("#sidebar-content").appendTo("#side-act-content"),f=!0,console.log("sadasd"));768<c&&f&&
($("#sidebar-content").appendTo("aside.sidebar"),f=!1)};this.$window.scroll(function(){c=a.$window.scrollTop();!d&&c<e?(b.removeClass("hidden"),d=!0):d&&c>e&&(b.addClass("hidden"),d=!1,h());e=c}).resize(function(){l()});k.click(function(a){a.preventDefault();h(!0)});l();$("menu.main a").each(function(a){$(this).addClass("it-menu"+a)});return this},currentMenu:function(){var a=this.$article.attr("currentmenu");$("menu.main a").each(function(){var b=$(this);-1!=b.text().toLowerCase().indexOf(a)&&b.addClass("current")});
return this},wpCaptionOnFull:function(){var a=$("img.size-full");a.parent(".wp-caption").css("max-width",a.width()+"px");return this},disableButtons:function(){$(".button.disable").attr("title","").click(function(a){(a||window.event).preventDefault();return!1});return this},portfolioGrid:function(){new cazuGrid("#gallery");return this},portfolioItemAjax:function(){var a=this,b=$(".item-show"),e=$("#item-dimmer"),c=$("#item-content").css("min-height",a.$window.height()+"px"),d=c.html(),k=function(d,
f){a.$body.addClass("overflow-hidden");b.scrollTop(0).fadeIn(400,function(){});$.ajax({url:"http://"+server+"/singleportfolio/",data:{id:d,urlpost:f},type:"POST",success:function(a){c.html(a);b.scrollTop(0);e.height(c.height())},error:function(){window.location.href=f},complete:function(){a.preHighlight().validateForm();$.getScript("//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4d9270a3495656e9",function(){addthis.toolbox(".addthis_toolbox")})}})},g=function(){b.fadeOut(250,function(){a.$body.removeClass("overflow-hidden");
c.html(d)})};$.ajaxSetup({cache:!1});$(".open-work").click(function(a){(a||window.event).preventDefault();k($(this).attr("rel"),$(this).attr("href"));return!1});$(".close-work").click(function(){g();return!1});b.scroll(function(){e.height(c.height())});return this},searchForm:function(){var a=$("#searchform");a.find("#s").attr("placeholder","Search").val("").focus(function(){a.addClass("focus")}).blur(function(){a.removeClass("focus")});return this},validateForm:function(){var a=$("fieldset.validate"),
b=!0,e=function(){b=!0;a.each(function(){var a=$(this),d=a.find("input,textarea"),e=parseInt(a.attr("min"))||0,g=d.val(),h=/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,f=!1;a.hasClass("email")&&(f=!0);g.length<e?(b=!1,a.addClass("error"),d.focus()):a.removeClass("error");f&&(-1==g.search(h)?(b=!1,a.addClass("error"),d.focus()):a.removeClass("error"))})};$("#submit").click(function(a){e();b||a.preventDefault()});$("#clearFields").click(function(b){b.preventDefault();a.removeClass("error").find("input,textarea").val("");
a.eq(0).find("input").focus()});return this},preHighlight:function(){0<$("pre").not(".no-print").addClass("prettyprint").each(function(){$(this).text($(this).html())}).length&&$.getScript("//google-code-prettify.googlecode.com/svn/loader/run_prettify.js");return this},wipSlide:function(){0<$(".wipSlider").length&&$.getScript(templateURL+"/js/jquery.wipSlider.min.js",function(){$(".wipSlider").wipSlider()});return this},getBubble:function(){$.getScript(templateURL+"/js/jquery.bubble.js",function(){$(".bubble").Bubble()});
return this}};$("document").ready(function(){cazu.init()});
<?php if(extension_loaded('zlib')){ob_end_flush();}?>